export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_FAILED='GET_EVENTS_FAILED';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED';
export const RESET_IS_DELETED='RESET_IS_DELETED';

export const FINISHED_GET_EVENTS='FINISHED_GET_EVENTS';

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const UPLOAD_FORM_DATA_SUCCESS ='UPLOAD_FORM_DATA_SUCCESS ';
export const UPLOAD_FORM_DATA_FAILED='UPLOAD_FORM_DATA_FAILED';

export const UPLOAD_RESERVATION_SUCCESS='UPLOAD_RESERVATION_SUCCESS';
export const UPLOAD_RESERVATION_FAILED='UPLOAD_RESERVATION_FAILED';
export const UPLOAD_RESERVATION='UPLOAD_RESERVATION';

export const DOWNLOAD_RESERVATION_SUCCESS='DOWNLOAD_RESERVATION_SUCCESS';
export const DOWNLOAD_RESERVATION_FAILED='DOWNLOAD_RESERVATION_FAILED';
export const DOWNLOAD_RESERVATION='DOWNLOAD_RESERVATION';

export const DELETE_RESERVATION_SUCCESS='DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_FAILED='DELETE_RESERVATION_FAILED';
export const DELETE_RESERVATION='DELETE_RESERVATION';

export const STATE_OF_TABLE='STATE_OF_TABLE';
export const STATE_OF_TABLE_DELETE='STATE_OF_TABLE_DELETE';

export const RESET_PATH_RESERVATION='RESET_PATH_RESERVATION';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const ADMIN_SUCCESS='ADMIN_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';


